version: "3"

services:
  vpn:
    image: jeroenslot/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ovpn-data:/app/ovpn/config
    environment:
      TZ: Europe/Paris
      USERNAME: "${NORDVPN_USERNAME}"
      PASSWORD: "${NORDVPN_PASSWORD}"
      LOCAL_NETWORK: 192.168.1.0/24
      # Could not get "UK" to work.
      COUNTRY: US
    ports:
      - "8118:8118"
    restart: always

    networks:
      - default
  chrome:
    image: selenium/standalone-chrome:4.0
    depends_on:
      - vpn
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 3gb
    #environment:
    #  # https://stackoverflow.com/questions/43395659/properties-for-selenium-grid-hub-node-config/43412373#43412373
    #  # SE_OPTS: "--max-sessions=1 "


volumes:
  ovpn-data:
